### ISSUE TITLE
[Insight] Web applications should contain a favicon

### ISSUE THREAD

**Issue by dave1010** [PHPDorset/phpdorset.github.io#39]
**[in web/](https://github.com/dave1010/phpdorset.github.io/blob/master/web#L0)**

> No favicon found in the web root directory

```

web/
├── fonts/
├── images/
├── stylesheets/
└── index.php
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f3cb641-3d5e-4f04-853d-25cf2596b648/analyses/1)_

**Comment by dave1010** [comment]
cp web/images/favicon.ico web/favicon.ico

**Comment by christiansherry** [comment]
@dave1010 resolved in https://github.com/PHPDorset/phpdorset.github.io/pull/51
