### ISSUE TITLE
Put more talks online

### ISSUE THREAD

**Issue by dave1010** [PHPDorset/phpdorset.github.io#47]
cc @christiansherry

**Comment by christiansherry** [comment]
I'll sort them out Monday, will need to clear with jenny putting hers up

**Comment by rossey** [comment]
We also need to look at a redesign of the website which will help with this too

**Comment by christiansherry** [comment]
Micheal Cullums talk has no video unfortunately, the file was corrupt when I came to get it off the card :(

**Comment by christiansherry** [comment]
Jenny Wong - Dec (with video, pending approval)
Michael Cullum - Feb
 Any others missing?
